name: On Push
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
